routes/web.php
<?php

use Sautor\Testimonials\Controllers\CollectionController;
use Sautor\Testimonials\Controllers\PublicController;
use Sautor\Testimonials\Controllers\TestimonialController;

Sautor\groupRoute(function() {
    Route::middleware('addon:testimonials')->name('testimonials.')->prefix('testemunhos')->group(function() {
        Route::get('/', [PublicController::class, 'index'])->name('public.index');

        Route::resource('collections', CollectionController::class)->middleware('auth');

        Route::get('{collection}', [PublicController::class, 'create'])->name('public.create');

        Route::get('testimonials/{testimonial}', [TestimonialController::class, 'show'])->middleware('auth')->name('testimonials.show');
        Route::get('testimonials/{testimonial}/edit', [TestimonialController::class, 'edit'])->middleware('auth')->name('testimonials.edit');
        Route::put('testimonials/{testimonial}', [TestimonialController::class, 'update'])->middleware('auth')->name('testimonials.update');

    });
});

resources/views/collections/create.blade.php
@extends('layouts.group-admin')

@section('group-content')
    <header class="group-page__header">
        <h1 class="group-page__header__title">
            Criar coleção de testemunhos
        </h1>
    </header>

    @php($scope = 'new-collection')
    <form action="{{ $grupo->route('testimonials.collections.store') }}" method="POST" enctype="multipart/form-data" data-vv-scope="{{ $scope }}">
        @csrf

        @include('testimonials::collections.form')

        <div class="sautor-addon__actions">
            <button type="submit" class="button button--primary">Criar</button>
        </div>
    </form>
@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('addons/testimonials/styles.css') }}">
@endpush

resources/views/collections/edit.blade.php
@extends('layouts.group-admin')

@section('group-content')
    <header class="group-page__header">
        <h1 class="group-page__header__title">
            Editar coleção de testemunhos
        </h1>
    </header>

    @php($scope = 'edit-collection')
    <form action="{{ $grupo->route('testimonials.collections.update', $collection) }}" method="POST" data-vv-scope="{{ $scope }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        @include('testimonials::collections.form')

        <div class="sautor-addon__actions">
            <button type="submit" class="button button--primary">Editar</button>
            @can('delete', $collection)
                <button type="button" class="button button--danger-light" @click.prevent="openModal('deleteModal')">
                    <span class="far fa-trash mr-2"></span>
                    Eliminar
                </button>
            @endcan
        </div>
    </form>

    @can('delete', $collection)
        <modal id="deleteModal">
            <div class="modal__body modal__confirmation">
                <div class="modal__confirmation__icon">
                    <span class="fas fa-exclamation"></span>
                </div>
                <div class="modal__confirmation__content">
                    <h3 class="modal__confirmation__title">Eliminar coleção de testemunhos</h3>
                    <p class="modal__confirmation__text">
                        Tem a certeza que quer eliminar a coleção <strong>{{ $collection->name }}</strong>?
                    </p>
                </div>
            </div>
            <form class="modal__footer" method="POST" action="{{ $collection->grupo->route('testimonials.collections.destroy', $collection) }}">
                @csrf
                @method('DELETE')
                <button type="submit" class="button button--danger">Eliminar</button>
                <button type="button" class="button" @click.prevent="closeModal('deleteModal')">Cancelar</button>
            </form>
        </modal>
    @endcan
@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('addons/testimonials/styles.css') }}">
@endpush

resources/views/collections/form.blade.php
@php($locales = ['pt' => 'Português', 'es' => 'Espanhol', 'en' => 'Inglês'])

<div class="s-tst-grid s-tst-grid-cols-1 md:s-tst-grid-cols-2 s-tst-gap-x-8">
    <x-forms.input name="open_at" label="Abrir a" :value="isset($collection) ? $collection->open_at : null"
                   type="datetime-local" :scope="$scope"/>
    <x-forms.input name="close_at" label="Fechar a" :value="isset($collection) ? $collection->close_at : null"
                   type="datetime-local" :scope="$scope"/>

    <div class="lg:s-tst-col-span-2">
        <x-forms.input name="tags" label="Etiquetas" :value="isset($collection) ? $collection->tags : null" hint="Escrever as etiquetas separadas por ;" :scope="$scope" />
    </div>

    <div>
        <h4 class="title title--xs s-tst-mb-3">Línguas</h4>
        @foreach($locales as $code => $locale)
            <x-forms.checkbox name="languages[]" :id="'languages['.$code.']'" :label="$locale" :value="isset($collection) ? isset($collection->languages) && in_array($code, $collection->languages) : null" :cb-val="$code" :scope="$scope" />
        @endforeach
    </div>

    <div>
        <h4 class="title title--xs s-tst-mb-3">Outras opções</h4>
        <x-forms.checkbox name="accept_audio" label="Aceitar áudio" :value="isset($collection) ? $collection->accept_audio : null" :scope="$scope" />
        <x-forms.checkbox name="accept_images" label="Aceitar imagens" :value="isset($collection) ? $collection->accept_images : null" :scope="$scope" />
        <x-forms.file name="banner" label="Banner" accept=".png,.jpg,.jpeg"
                      rules="ext:png,jpg,jpeg" :scope="$scope" />
    </div>
</div>

@foreach($locales as $code => $locale)
    <h3 class="title title--sm s-tst-my-4">{{ $locale }}</h3>

    <div class="s-tst-grid s-tst-grid-cols-1 md:s-tst-grid-cols-2 s-tst-gap-x-8">
        <x-forms.input
            :name="'name['.$code.']'"
            label="Nome"
            :value="isset($collection) ? $collection->getTranslation('name', $code, false) : null"
            required
            :scope="$scope"
        />
        @foreach(['opening_text' => 'Texto de abertura', 'disclaimer' => 'Aviso', 'thankyou_text' => 'Mensagem de agradecimento'] as $key => $label)
        <div class="field">
            <label class="label">{{ $label }}</label>
            <div class="control">
                <small-content-editor name="{{ $key.'['.$code.']' }}"
                                      value="{{ isset($collection) ? $collection->getTranslation($key, $code, false) : null }}"
                                      simple></small-content-editor>
            </div>
        </div>
        @endforeach
    </div>
@endforeach

resources/views/collections/index.blade.php
@extends('layouts.group-admin')

@section('group-content')
    <div class="group-page__header">
        <h1 class="group-page__header__title">
            Coleções de testemunhos
        </h1>

        <div class="group-page__header__actions">
            <a href="{{ $grupo->route('testimonials.collections.create') }}" class="button button--responsive">
                <span class="far fa-comment-plus"></span>
                Nova coleção
            </a>
        </div>
    </div>

    @include('testimonials::collections.list-component', ['actions' => fn ($tc) => [
        ['label' => 'Editar', 'icon' => 'fas fa-pencil', 'link' => $tc->grupo->route('testimonials.collections.edit', $tc)]
    ]])

@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('addons/testimonials/styles.css') }}">
@endpush

resources/views/collections/list-component.blade.php
@unless($collections->isEmpty())
    <section class="sautor-list sheets-list">
        @foreach($collections as $collection)
            <div class="sautor-list__item">
                <div class="sautor-list__item__logo">
                    <span class="sautor-list__item__logo__icon sautor-list__item__logo__icon--strong">
                        <span class="fad fa-comments fa-swap-opacity"></span>
                    </span>
                </div>
                <a href="{{ $collection->grupo->route('testimonials.collections.show', $collection) }}" class="sautor-list__item__data">
                    <p class="sautor-list__item__name">
                        {{ $collection->name }}
                    </p>
                    <p class="sautor-list__item__meta">
                        {{ $collection->testimonials->count() }} testemunhos
                        @if($collection->isOpen)
                            <span class="badge badge--success">Aberto</span>
                        @elseif($collection->isClosed)
                            <span class="badge badge--danger">Fechado</span>
                        @else
                            <span class="badge">Por abrir</span>
                        @endif
                    </p>
                </a>

                <div class="sautor-list__item__actions">
                    @unless(empty($actions) or empty($a = $actions($collection)))
                        @foreach($a as $action)
                            <a title="{{ $action['label'] }}"
                               @if(!empty($action['link']))
                                   href="{{ $action['link'] }}"
                               @elseif(!empty($action['modal']))
                                   href="#" data-toggle="modal" data-target="#{{ $action['modal'] }}"
                                    @endif
                            >
                                <span class="{{ $action['icon'] }}"></span>
                            </a>
                        @endforeach
                    @endunless
                    <a title="Ver" href="{{ $collection->grupo->route('testimonials.collections.show', $collection) }}">
                        <span class="far fa-angle-right"></span>
                    </a>
                </div>
            </div>
        @endforeach
    </section>
@else
    <section class="sautor-list--empty tags-list--empty">
        {{ empty($empty_message) ? 'Não existem coleções.' : $empty_message }}
    </section>
@endunless

resources/views/collections/show.blade.php
@extends('layouts.group-admin')

@section('group-content')
    <div class="group-page__header">
        <h1 class="group-page__header__title">
            {{ $collection->name }}
            <small>{{ $collection->testimonials_count }} testemunhos</small>
        </h1>

        <div class="group-page__header__actions">
            <a href="{{ $grupo->route('testimonials.collections.edit', $collection) }}" class="button button--responsive">
                <span class="fas fa-pencil"></span>
                Editar
            </a>
        </div>
    </div>


    @include('testimonials::testimonials.list-component')

    {!! $testimonials->links() !!}

@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('addons/testimonials/styles.css') }}">
@endpush

resources/views/testimonials/edit.blade.php
@extends('layouts.group-admin')

@section('group-content')
    <form action="{{ $grupo->route('testimonials.testimonials.update', $testimonial) }}" method="POST">
        @method('PUT')
        @csrf

        <div class="group-page__header">
            <h1 class="group-page__header__title">
                Editar testemunho #{{ $testimonial->id }}
                <small>{{ $testimonial->collection->name }}</small>
            </h1>

            <div class="group-page__header__actions">
                <button type="submit"
                   class="button button--primary button--responsive">
                    <span class="far fa-check"></span>
                    Gravar
                </button>
            </div>
        </div>

        <div class="people-show__tab__card">
            <p class="people-show__item">
                <span class="people-show__item__label">Nome</span>
                {{ $testimonial->name }}
            </p>
            <div class="s-tst-grid md:s-tst-grid-cols-2 s-tst-gap-6">
                <p class="people-show__item">
                    <span class="people-show__item__label">Endereço de email</span>
                    @empty($testimonial->email)
                        <span class="people-show__item__empty">(não especificado)</span>
                    @else
                        {{ $testimonial->email }}
                    @endempty
                </p>
                <p class="people-show__item">
                    <span class="people-show__item__label">Número de telefone</span>
                    @empty($testimonial->phone)
                        <span class="people-show__item__empty">(não especificado)</span>
                    @else
                        {{ $testimonial->phone->formatForCountry('PT') }}
                    @endempty
                </p>
            </div>
            <p class="people-show__item">
                <span class="people-show__item__label">Paróquia e/ou grupos</span>
                {{ $testimonial->origin }}
            </p>
            <p class="people-show__item">
                <span class="people-show__item__label">Etiquetas</span>
                @if($testimonial->tagsWithType($testimonial->collection->tagType)->isEmpty())
                    <span class="people-show__item__empty">(não especificado)</span>
                @else
                    {{ $testimonial->tagsWithType($testimonial->collection->tagType)->pluck('name')->join(', ') }}
                @endif
            </p>
            <div class="s-tst-grid md:s-tst-grid-cols-2 s-tst-gap-6">
                <div class="people-show__item">
                    <span class="people-show__item__label">Carregado por</span>
                    @empty($testimonial->pessoa)
                        <span class="people-show__item__empty">IP: {{ $testimonial->ip }} (sem sessão iniciada)</span>
                    @else
                        <x-people.show :person="$testimonial->pessoa" :meta="'IP:'.$testimonial->ip"/>
                    @endempty
                </div>
                <div class="people-show__item">
                    <span class="people-show__item__label">Revisor</span>
                    <pessoa-picker grupo-id="{{ $testimonial->collection->grupo_id }}"
                                   value="{{ $testimonial->reviewer_id }}" with-input name="reviewer_id"/>
                </div>
            </div>
        </div>

        <div class="s-tst-grid lg:s-tst-grid-cols-2 s-tst-gap-6">

            <div>
                @if($testimonial->hasMedia('audio'))
                    <header class="people-show__tab__header">
                        <h2 class="people-show__tab__title">Ficheiro áudio</h2>
                    </header>
                    <div class="people-show__tab__card">
                        <audio controls src="{{ $testimonial->getFirstMediaUrl('audio') }}"></audio>
                    </div>
                @else
                    <header class="people-show__tab__header">
                        <h2 class="people-show__tab__title">Conteúdo</h2>
                    </header>
                    <div class="people-show__tab__card">
                        <div class="prose whitespace-pre-line">{!! $testimonial->content !!}</div>
                    </div>
                @endif
            </div>

            <div>
                <header class="people-show__tab__header">
                    <h2 class="people-show__tab__title">Conteúdo revisto</h2>
                </header>
                <div class="s-tst-mb-8 s-tst-grid" x-data="{ content: '' }">
                    <div class="input s-tst-py-2 s-tst-px-3 s-tst-text-base s-tst-whitespace-pre-wrap"
                         style="visibility: hidden; grid-area: 1/1/2/2;" x-html="content">
                    </div>
                    <textarea name="reviewed_content" x-model="content"
                              class="input s-tst-min-h-[10rem] s-tst-resize-none"
                              style="grid-area: 1/1/2/2;">{!! $testimonial->reviewed_content !!}</textarea>
                </div>
            </div>

        </div>

        <header class="people-show__tab__header">
            <h2 class="people-show__tab__title">Notas</h2>
        </header>
        <div class="s-tst-mb-8">
            <div class="s-tst-mb-8 s-tst-grid" x-data="{ content: '' }">
                <div class="input s-tst-py-2 s-tst-px-3 s-tst-text-base s-tst-whitespace-pre-wrap"
                     style="visibility: hidden; grid-area: 1/1/2/2;" x-html="content">
                </div>
                <textarea name="notes" x-model="content" class="input s-tst-min-h-[10rem] s-tst-resize-none"
                          style="grid-area: 1/1/2/2;">{!! $testimonial->notes !!}</textarea>
            </div>
        </div>

        @if($testimonial->hasMedia('images'))
            <header class="people-show__tab__header">
                <h2 class="people-show__tab__title">Fotografias</h2>
            </header>

            <div class="s-tst-grid s-tst-grid-cols-3 md:s-tst-grid-cols-4 lg:s-tst-grid-cols-5 xl:s-tst-grid-cols-6 s-tst-gap-4">
                @foreach($testimonial->getMedia('images') as $image)
                    <a href="{{ $image->getUrl() }}" target="_blank">
                        <img src="{{ $image->getUrl() }}"
                             class="s-tst-w-full s-tst-aspect-square s-tst-rounded s-tst-object-cover s-tst-border s-tst-border-gray-300">
                    </a>
                @endforeach
            </div>
        @endif

    </form>

@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('addons/testimonials/styles.css') }}">
@endpush

resources/views/testimonials/list-component.blade.php
@unless($testimonials->isEmpty())
    <section class="sautor-list sheets-list">
        @foreach($testimonials as $testimonial)
            <div class="sautor-list__item">
                <div class="sautor-list__item__logo">
                    <span class="sautor-list__item__logo__icon sautor-list__item__logo__icon--strong">
                        <span class="fad {{ $testimonial->hasMedia('audio') ? 'fa-comment-music' : 'fa-comment-lines' }}"></span>
                    </span>
                </div>
                <a href="{{ $testimonial->collection->grupo->route('testimonials.testimonials.show', $testimonial) }}" class="sautor-list__item__data">
                    <p class="sautor-list__item__name">
                        {{ $testimonial->name }}
                    </p>
                    <p class="sautor-list__item__meta">
                        {{ $testimonial->origin }}

                        @if($testimonial->tagsWithType($testimonial->collection->tagType)->isNotEmpty())
                            &middot; <span class="far fa-tag"></span> {{ $testimonial->tagsWithType($testimonial->collection->tagType)->count() }}
                        @endif

                        @if($testimonial->hasMedia('images'))
                            &middot; <span class="far fa-images"></span> {{ $testimonial->getMedia('images')->count() }}
                        @endif

                        @if($testimonial->reviewer)
                            &middot; <span class="s-tst-text-primary-600">A ser revisto por {{ $testimonial->reviewer->nome_curto }}</span>
                        @endif
                    </p>
                </a>

                <div class="sautor-list__item__actions">
                    @unless(empty($actions) or empty($a = $actions($collection)))
                        @foreach($a as $action)
                            <a title="{{ $action['label'] }}"
                               @if(!empty($action['link']))
                                   href="{{ $action['link'] }}"
                               @elseif(!empty($action['modal']))
                                   href="#" data-toggle="modal" data-target="#{{ $action['modal'] }}"
                                    @endif
                            >
                                <span class="{{ $action['icon'] }}"></span>
                            </a>
                        @endforeach
                    @endunless
                    <a title="Ver" href="{{ $testimonial->collection->grupo->route('testimonials.testimonials.show', $testimonial) }}">
                        <span class="far fa-angle-right"></span>
                    </a>
                </div>
            </div>
        @endforeach
    </section>
@else
    <section class="sautor-list--empty tags-list--empty">
        {{ empty($empty_message) ? 'Não existem testemunhos.' : $empty_message }}
    </section>
@endunless

resources/views/testimonials/show.blade.php
@extends('layouts.group-admin')

@section('group-content')
    <div class="group-page__header">
        <h1 class="group-page__header__title">
            Testemunho #{{ $testimonial->id }}
            <small>{{ $testimonial->collection->name }}</small>
        </h1>

        <div class="group-page__header__actions">
            <a href="{{ $grupo->route('testimonials.testimonials.edit', $testimonial) }}" class="button button--responsive">
                <span class="far fa-comment-check"></span>
                Rever
            </a>
        </div>
    </div>

    <div class="people-show__tab__card">
        <p class="people-show__item">
            <span class="people-show__item__label">Nome</span>
            {{ $testimonial->name }}
        </p>
        <div class="s-tst-grid md:s-tst-grid-cols-2 s-tst-gap-6">
            <p class="people-show__item">
                <span class="people-show__item__label">Endereço de email</span>
                @empty($testimonial->email)
                    <span class="people-show__item__empty">(não especificado)</span>
                @else
                    {{ $testimonial->email }}
                @endempty
            </p>
            <p class="people-show__item">
                <span class="people-show__item__label">Número de telefone</span>
                @empty($testimonial->phone)
                    <span class="people-show__item__empty">(não especificado)</span>
                @else
                    {{ $testimonial->phone->formatForCountry('PT') }}
                @endempty
            </p>
        </div>
        <p class="people-show__item">
            <span class="people-show__item__label">Paróquia e/ou grupos</span>
            {{ $testimonial->origin }}
        </p>
        <p class="people-show__item">
            <span class="people-show__item__label">Etiquetas</span>
            @if($testimonial->tagsWithType($testimonial->collection->tagType)->isEmpty())
                <span class="people-show__item__empty">(não especificado)</span>
            @else
                {{ $testimonial->tagsWithType($testimonial->collection->tagType)->pluck('name')->join(', ') }}
            @endif
        </p>
        <div class="s-tst-grid md:s-tst-grid-cols-2 s-tst-gap-6">
            <div class="people-show__item">
                <span class="people-show__item__label">Carregado por</span>
                @empty($testimonial->pessoa)
                    <span class="people-show__item__empty">IP: {{ $testimonial->ip }} (sem sessão iniciada)</span>
                @else
                    <x-people.show :person="$testimonial->pessoa" :meta="'IP:'.$testimonial->ip" />
                @endempty
            </div>
            <div class="people-show__item">
                <span class="people-show__item__label">Revisor</span>
                @empty($testimonial->reviewer)
                    <span class="people-show__item__empty">(sem revisor associado)</span>
                @else
                    <x-people.show :person="$testimonial->reviewer" />
                @endempty
            </div>
        </div>
    </div>

    <div class="s-tst-grid lg:s-tst-grid-cols-2 s-tst-gap-6">

        <div>
            @if($testimonial->hasMedia('audio'))
                <header class="people-show__tab__header">
                    <h2 class="people-show__tab__title">Ficheiro áudio</h2>
                </header>
                <div class="people-show__tab__card">
                    <audio controls src="{{ $testimonial->getFirstMediaUrl('audio') }}"></audio>
                </div>
            @else
                <header class="people-show__tab__header">
                    <h2 class="people-show__tab__title">Conteúdo</h2>
                </header>
                <div class="people-show__tab__card">
                    <div class="prose whitespace-pre-line">{!! $testimonial->content !!}</div>
                </div>
            @endif
        </div>

        <div>
            <header class="people-show__tab__header">
                <h2 class="people-show__tab__title">Conteúdo revisto</h2>
            </header>
            <div class="people-show__tab__card">
                <div class="prose s-tst-whitespace-pre-line">{!! $testimonial->reviewed_content !!}</div>
            </div>
        </div>

    </div>

    @unless(empty($testimonial->notes))
        <header class="people-show__tab__header">
            <h2 class="people-show__tab__title">Notas</h2>
        </header>
            <div class="prose s-tst-whitespace-pre-line s-tst-mb-8 s-tst-italic s-tst-font-accent s-tst-text-gray-700">{!! $testimonial->notes !!}</div>
    @endunless

    @if($testimonial->hasMedia('images'))
        <header class="people-show__tab__header">
            <h2 class="people-show__tab__title">Fotografias</h2>
        </header>

        <div class="s-tst-grid s-tst-grid-cols-3 md:s-tst-grid-cols-4 lg:s-tst-grid-cols-5 xl:s-tst-grid-cols-6 s-tst-gap-4">
            @foreach($testimonial->getMedia('images') as $image)
                <a href="{{ $image->getUrl() }}" target="_blank">
                    <img src="{{ $image->getUrl() }}" class="s-tst-w-full s-tst-aspect-square s-tst-rounded s-tst-object-cover s-tst-border s-tst-border-gray-300" >
                </a>
            @endforeach
        </div>
    @endif

@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('addons/testimonials/styles.css') }}">
@endpush